apiVersion: v1
kind: Secret
metadata:
  name: nginx-example-tls-secret
  namespace: default
data:
  tls.crt: CHANGEME_MYDOMAIN_PUBLIC_CERT
  tls.key: CHANGEME_MYDOMAIN_PRIV_KEY
type: kubernetes.io/tls
